### ISSUE TITLE
Adding a waypoint for homing after push actions

### ISSUE THREAD

**Issue by jypuigbo** [robotology/wysiwyd#163]
It would be safer to have an intermediate waypoint for going to `home` position after a push action. 
Maybe @towardthesea could help on that?

The changes for this behavior are being made in the branch `feature/upf/pushBehaviors`.

**Comment by towardthesea** [comment]
Hi @jypuigbo, @sockchinglow  
A new method was added to `subSystem_KARMA` to return robot arm after any push actions (but before home call). It was tested in IIT without any problem.
Could you please check it with `behaviorManager`! Then we can make a PR!

Cheers,
Phuong

**Comment by Tobias-Fischer** [comment]
Was this tested in the meantime? Can we merge?

**Comment by towardthesea** [comment]
@Tobias-Fischer I tested in IIT but still waiting the full test of UPF with behaviorManager. Should we wait?

**Comment by clement-moulin-frier** [comment]
Hi,

Sorry guys we have been delayed a lot these last weeks. The rush is ending tomorrow, so Monday we test it sure (our iCub is working fine now).

Clément

**Comment by pattacini** [comment]
Hi @clement-moulin-frier,

Then, do you have any news on https://github.com/robotology/icub-support/issues/321?

**Comment by jypuigbo** [comment]
It is solved!

**Comment by pattacini** [comment]
Thanks!

**Comment by Tobias-Fischer** [comment]
Does that mean you tested this and we can close the issue @jypuigbo? 
To be honest, I am still not sure whether this issue exists just to test something which is already in `devel`, or test something in another branch which still needs to be merged into `devel`. Could you please let me know @towardthesea?

**Comment by clement-moulin-frier** [comment]
Hi,

We are testing the push behaviors now.
@towardthesea : to do so, do you confirm we have to run the modules in `main/src/examples/KARMAiCubClientExample/KARMAiCubClientExample.xml`?
from the branch `feature/upf/pushBehaviors`

**Comment by sockchinglow** [comment]
@towardthesea we did not see any further problems with this during the test. Thanks!
